services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pmapp}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pmapp}
      POSTGRES_DB: ${POSTGRES_DB:-pmdb}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-pmapp}:${POSTGRES_PASSWORD:-pmapp}@db:5432/${POSTGRES_DB:-pmdb}
      SECRET_KEY: ${SECRET_KEY:-devsecret}
      ACCESS_TOKEN_EXPIRE_MINUTES: "120"
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:5174}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:8000/api/v1}
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  dbdata:
