# APM Server Configuration for PM AI MVP

# Server settings
apm-server:
  host: "0.0.0.0:8200"
  max_header_size: 1048576
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  max_event_size: 307200
  max_connections: 0
  response_headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block

# Output configuration
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "apm-%{+yyyy.MM.dd}"
  template.name: "apm"
  template.pattern: "apm-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0
    index.codec: best_compression

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/apm-server/logs
  name: apm-server
  keepfiles: 7
  permissions: 0644

# Monitoring configuration
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

# Setup configuration
setup.kibana:
  host: "kibana:5601"

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression

# ILM configuration
setup.ilm.enabled: true
setup.ilm.rollover_alias: "apm"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy: "apm-policy"

# Dashboard configuration
setup.dashboards.enabled: true
setup.dashboards.directory: /usr/share/apm-server/kibana

# Instrumentation configuration
instrumentation:
  enabled: true

# Queue configuration
queue.mem:
  events: 4096
  flush.min_events: 0
  flush.timeout: 1s

# Performance tuning
max_procs: 0

# Security settings
apm-server.secret_token: ""

# Data retention
apm-server.data_streams.enabled: true
apm-server.data_streams.wait_for_integration: true

# Sampling configuration
apm-server.sampling:
  keep_unsampled: true
  tail:
    enabled: true
    interval: 1m
    storage_limit: 1gb

# Agent configuration
apm-server.agent.config:
  cache:
    expiration: 30s
  etag:
    expiration: 1m

# RUM configuration
apm-server.rum:
  enabled: true
  allow_origins: ["*"]
  allow_headers: ["*"]
  source_mapping:
    cache:
      expiration: 5m
    index_pattern: "apm-*-sourcemap*"

# Kibana configuration
apm-server.kibana:
  enabled: true
  host: "kibana:5601"

# Jaeger configuration
apm-server.jaeger:
  grpc:
    enabled: true
    host: "0.0.0.0:14250"
  http:
    enabled: true
    host: "0.0.0.0:14268"

# OTLP configuration
apm-server.otlp:
  grpc:
    enabled: true
    host: "0.0.0.0:4317"
  http:
    enabled: true
    host: "0.0.0.0:4318"

# Profiling configuration
apm-server.profiling:
  enabled: true
  tail:
    enabled: true
    interval: 1m
    storage_limit: 1gb

# Fleet configuration
apm-server.fleet:
  enabled: true
  host: "kibana:5601"
