# Metricbeat Configuration for PM AI MVP

# Module configuration
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

# System module
metricbeat.modules:
  # System metrics
  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - socket_summary
      - filesystem
      - fsstat
    enabled: true
    period: 10s
    processes: ['.*']
    process.include_top_n:
      by_cpu: 5
      by_memory: 5
    process.include_per_cpu: true
    process.cmdline.cache.enabled: true
    process.cmdline.cache.ttl: 5m
    process.env.whitelist: [".*"]
    process.include_cpu_ticks: true

  # Docker module
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  # Elasticsearch module
  - module: elasticsearch
    metricsets:
      - node
      - node_stats
      - cluster_stats
      - index
      - index_recovery
      - index_summary
      - ml_job
      - shard
    period: 10s
    hosts: ["http://elasticsearch:9200"]
    enabled: true

  # Logstash module
  - module: logstash
    metricsets:
      - node
      - node_stats
    period: 10s
    hosts: ["http://logstash:9600"]
    enabled: true

  # Kibana module
  - module: kibana
    metricsets:
      - stats
    period: 10s
    hosts: ["http://kibana:5601"]
    enabled: true

  # PostgreSQL module
  - module: postgresql
    metricsets:
      - database
      - bgwriter
      - activity
      - replication
    period: 10s
    hosts: ["postgresql://pmapp:pmapp@db:5432/pmdb"]
    enabled: true

  # Redis module
  - module: redis
    metricsets:
      - info
      - keyspace
      - memory
      - persistence
      - replication
      - stats
    period: 10s
    hosts: ["redis:6379"]
    password: "${REDIS_PASSWORD:-}"
    enabled: true

  # Nginx module
  - module: nginx
    metricsets:
      - stubstatus
    period: 10s
    hosts: ["http://nginx:80/nginx_status"]
    enabled: true

  # HTTP module
  - module: http
    metricsets:
      - json
    period: 10s
    hosts: ["http://backend:8000/health"]
    namespace: "backend"
    path: "/health"
    method: "GET"
    enabled: true

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

# Output configuration
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "pm-ai-metrics-%{+yyyy.MM.dd}"
  template.name: "pm-ai-metrics"
  template.pattern: "pm-ai-metrics-*"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/metricbeat/logs
  name: metricbeat
  keepfiles: 7
  permissions: 0644

# Monitoring configuration
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]

# Setup configuration
setup.kibana:
  host: "kibana:5601"

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression

# ILM configuration
setup.ilm.enabled: true
setup.ilm.rollover_alias: "pm-ai-metrics"
setup.ilm.pattern: "{now/d}-000001"
setup.ilm.policy: "pm-ai-metrics-policy"

# Dashboard configuration
setup.dashboards.enabled: true
setup.dashboards.directory: /usr/share/metricbeat/kibana

# Registry configuration
filebeat.registry.path: /usr/share/metricbeat/data/registry

# Queue configuration
queue.mem:
  events: 4096
  flush.min_events: 0
  flush.timeout: 1s

# Performance tuning
max_procs: 0
